### ISSUE TITLE
Doesn't run on OS X

### ISSUE THREAD

**Issue by stevew817** [ARMmbed/mbed-cloud-sdk-dotnet#167]
.NET Core 2 on OS X throws an exception on SecurityProtocolType.Ssl3, since it has been deprecated by Microsoft. Therefore, object instantiation of the Config class fails, and the whole API becomes unusable since there's no way to supply the requisite config object into any API constructor.

https://github.com/ARMmbed/mbed-cloud-sdk-dotnet/blob/844543a15c1ca9819cfed685d7426431746eb389/MbedCloudSDK/Common/Config.cs#L23

**Comment by madchutney** [comment]
Hi Steve, thanks for the feedback. We currently only support Mono but are looking at moving to .NET Core 2 as soon as possible, we'll keep you posted.

**Comment by alexl0gan** [comment]
@stevew817 please checkout the latest Nuget package [here](https://www.nuget.org/packages/Mbed.Cloud.SDK/1.2.4). We have updated the project to .NET Core 2.0 and would appreciate any feedback you have when you start using it.
